import Head from 'next/head'
import { useState } from 'react'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import styles from '../styles/Home.module.css'

export default function Home(results) {

  const initialState = results;
  const [characters, setCharacters] = useState(initialState.characters);

  import {
    Heading,
    Box,
    Flex,
    Input,
    Stack,
    IconButton,
    useToast
  } from "@chakra-ui/react";

  return (
    <div className={styles.container}>
      <Head>
        <title>Graphql Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql",
    cache: new InMemoryCache(),
  })
  const { data } = await client.query({
    query: gql`
    query{
      characters(page: 1){
        info{
          count
          pages
        }
        results{
          name
          id
          location{
            id
            name
          }
          origin{
            id
            name
          }
          episode{
            id
            episode
            air_date
          }
          image
        }
      }
    }
    `
  });

return {
  props : {
    characters : data.characters.results
  }
}
}
